config/routes.rb
Rails.application.routes.draw do
  
  match '/', to: 'page#index', via: [:get, :post], as: 'root'

  resources :comments, only: [:create, :update, :destroy], path: 'comment'
  
  post 'lab/:brand_id/:polish_id/rollback/:version_id', to: 'polishes#rollback', as: 'brand_polish_rollback'
  post 'vote/:votable_type/:votable_id', to: 'users#vote', as: 'vote'
  post 'note/:polish_id', to: 'polishes#note', as: 'note'
  post 'collect/:polish_id', to: 'polishes#collect', as: 'collect'
  post 'lock/:polish_id', to: 'polishes#lock', as: 'lock'
  post 'get_invite', to: 'users#get_invite'
  post 'switch/:switch/:option', to: 'user_sessions#switch', as: 'switch'
  patch 'boxes/:id', to: 'boxes#update', as: 'update_box'
  post ':user_id/download/:id', to: 'boxes#export', as: 'download_box'
  get 'find_related', to: 'polishes#find_related'
  get 'search', to: 'application#search'
  get 'lab_search', to: 'application#lab_search'
  match 'collection_search', to: 'application#collection_search', via: [:get, :post]
  match 'collect_search', to: 'application#collect_search', via: [:get, :post]
  get 'reorder', to: 'polishes#reorder'
  get 'autocomplete', to: 'application#autocomplete'
  get 'bottling_status/:id', to: 'polishes#get_bottling_status', as: 'get_bottling_status'
  get 'lab/maintenance', to: 'page#maintenance'
  get 'lab/bottle_list', to: 'bottles#index'
  get 'lab/user_list', to: 'users#index'
  match 'catalogue/colour_search', to: 'polishes#colour_search', as: 'colour_search', via: [:get, :post]

  resources :ads

  scope '/catalogue' do
    get '/', to: 'polishes#index', as: 'catalogue'
    constraints(id: /[^\/]+/) do
      get ':brand_id', to: 'brands#show', as: 'catalogue_brand'
      get ':brand_id/:polish_id', to: 'polishes#show', as: 'catalogue_brand_polish'
    end
  end
  
  scope '/lab' do
    constraints(id: /[^\/]+/) do
      resources :brands    , lab: 'true', param: 'brand_id', path: '' 
      resources :brands    , lab: 'true', only: [], path: '' do
        resources :polishes, lab: 'true', except: :index, param: 'polish_id', path: ''
        resources :polishes, lab: 'true', only: [], param: 'polish_id', path: '' do
          get :redress     , lab: 'true', on: :member
          get 'versions'   , lab: 'true', to: 'polish_versions#index', on: :member
          post :clone, on: :member
        end
        resources :bottles , lab: 'true', except: :index
      end
    end
  end

  resource :user_session, only: [:create, :destroy]
  resource :following, only: [:create, :destroy]
  
  constraints(id: /[^\/]+/) do
    resources :users, param: 'user_id', except: [:index, :create, :new], path: '' do
      get 'tags/:tag', to: 'entries#index', as: 'tag', on: :member
    end
    resources :users, path: '', only: [] do
      resources :boxes, except: [:index, :edit], path: '' do
        post :import, on: :member
        post :clear, on: :member
        get :gather, on: :member
        get :edit, on: :member, to: 'boxes#show', edit: true
      end
      resources :followings, only: [:create, :destroy]
      resources :entries, path: 'diary' do
        post :like, on: :member          
      end    
    end
  end  
  
end

app/models/user.rb
class User < ActiveRecord::Base
  include Slugify
  
  acts_as_authentic do |c|
    c.crypto_provider = Authlogic::CryptoProviders::BCrypt
    c.login_field = 'name'
    c.validate_email_field = false
    c.require_password_confirmation = false
  end
  
  attr_accessor :invite_phrase, :crop_coords

  before_validation :name_to_slug
  after_create :cancel_invite, :give_invites, :make_default_boxes
  
  has_many :invites, dependent: :destroy
  has_one  :invite, foreign_key: 'used_by'
  has_many :boxes, -> { order 'name ASC' }, dependent: :destroy
  has_many :notes, dependent: :destroy
  has_many :votes, class_name: 'UserVote', dependent: :destroy
  has_many :comments
  has_many :events, dependent: :destroy
  has_many :followings, foreign_key: 'followee_id', dependent: :destroy
  has_many :followers, through: :followings
  has_many :followeeings, foreign_key: 'follower_id', class_name: 'Following', dependent: :destroy
  has_many :followees, through: :followeeings

  validate :excluded_name?
  validate :valid_invite?, on: :create
  
  mount_uploader :avatar, AvatarUploader  

  def self.ghost
    new(name: I18n.t('Ghost'), slug: 'ghost')
  end

  def to_param; slug end
  
  def name_to_slug
    unless self.name.squish!.empty?
      self.slug = slugify(self.name)
    end
  end  
  
  private

  def valid_invite?
    if new_record?
      unless Defaults::SYSTEM_NAMES.include?(self.name) || User.count == 0 || Invite.where(used_by: nil, word: invite_phrase.try(:strip)).count > 0 
        errors.add(:invite_phrase, "to register you need to say the secret word")
      end
    end
  end
  def excluded_name?
    if Defaults::RESERVED_NAMES.include?( self.name)
      errors.add(:name, "You don't want to take that name here, #{name}")
    end
  end
  def cancel_invite
    invite = Invite.where(used_by: nil, word: invite_phrase.try(:strip)).first
    if invite
      invite.used_by = self.id
      invite.save
    end
    create_event invite
  end
  def give_invites; 2.times {Invite.give_to self}; end
  def make_default_boxes
    %w(collection giveaway wishlist).each{ |box| self.boxes.new(name: box).save }
  end
  def create_event invite
    Event.new(event_type: 'user', user_id: invite.user_id, author: name, eventable_id: self.id, eventable_type: 'User').save
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include Slugify
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
    if @user == current_user
      @events = @user.events.where('new = true OR updated_at > ?', Time.now - 1.day).order('created_at DESC')
      @events.each{|e| e.update(new: false)}
      @evented_polishes = Polish.find(@events.where(eventable_type: 'Polish').pluck(:eventable_id).uniq)
      @user.update(events_count: 0)
    end
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    if params[:preview]
      @user.assign_attributes(user_params)
      render :edit
    elsif params[:cancel]
      @user.assign_attributes(user_params.except(:avatar, :avatar_cache))
      render :edit
    else
      if @user.update user_params
        unless params[:user][:avatar_cache].blank? && params[:user][:avatar].blank?
          @user.avatar.big_thumb.crop_and_resize(params[:user][:crop_coords])
          @user.avatar.thumb.resize(@user.avatar.big_thumb)
        end
        redirect_to @user, notice: 'User was successfully updated.' 
      else
        render :edit
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def vote
    if current_user
      vote = current_user.votes.find_or_initialize_by(params.permit(:votable_type, :votable_id))
      old_vote = vote.new_record? ? 0 : vote.rating
      vote.rating = params[:vote] == 'up' ? 1 : params[:vote] == 'down' ? -1 : params[:vote].to_i < 1 ? 1 : params[:vote].to_i > 5 ? 5 : params[:vote].to_i
      
      case params[:votable_type]
      when 'Polish'
        vote.save
        (@polish = Polish.find(params[:votable_id])).calculate_rating
      when 'Comment'
        unless (@comment = Comment.find params[:votable_id]).user_id == current_user.id || old_vote == vote.rating
          @comment.rating += vote.rating
          @comment.save 
          vote.rating = 0 if (old_vote == 1 && vote.rating == -1) || (old_vote == -1 && vote.rating == 1)
          vote.save unless @comment.user_id == current_user.id
        end
      end
    end
  end

  def get_invite    
    @invite = Invite.give_to current_user if current_user
  end
  
  private
    def set_user
      @user = User.find_by_slug(slugify(params[:user_id]))
    end

    def user_params
      params.require(:user).permit(:name, :password, :invite_phrase, :about, :avatar, :crop_coords, :remove_avatar, :remote_avatar_url, :avatar_cache, :email, :role, :locale )
    end
end

app/views/users/_form.html.haml
= form_for @user, html: {id: 'signUp'} do |f|
  = f.text_field :name, placeholder: 'Name', id: 'signup_user_name'
  = f.text_field :password, placeholder: 'Password', autocomplete: 'off', id: 'signup_user_password'
  - unless User.count < 1
    = f.submit 'Sign Up', name: 'to_parole', disabled: @disabled
    = f.text_field :invite_phrase, placeholder: 'Invite code' 
  = f.submit 'sign up', disabled: @disabled
  = f.submit 'update', name: 'update', style: 'display:none'


= form_for @user, url: user_session_path, method: :post, html: {id: 'logIn'} do |f|
  = f.text_field :name, placeholder: 'Name', id: 'login_user_name'
  = f.password_field :password, placeholder: 'Password', autocomplete: 'off', id: 'login_user_password'
  = f.submit 'log in', disabled: @disabled
  = f.submit 'update', name: 'update', style: 'display:none'

app/views/users/edit.html.haml
.main
  %h1= t('settings.headers.profile')
  = form_for @user, html: { id: 'editForm', multipart: true, method: :put } do |f|
    .block.left
      .table.wide100
        .cell.wide100
          .resizable.relative
            = f.text_area :about, class: 'resizable', rows: nil, cols: nil, placeholder: t('placeholder.bio')
            %pre.resizable <span></span>
      .menuSpacer.inline 
      %ul#localeMenu.menu.furlable.inline.switch{'data-activate' => '#localeMenu'}
        - %w(en ru es de fr it).each do |l|
          %li{class: (l == I18n.locale.to_s ? 'current' : 'notCurrent')}= l.to_s 
        <svg class='icon switch'><use xlink:href=#down /></svg>
      = f.text_field :email, placeholder: t('placeholder.email'), class: 'smallMargin'
  
      = f.submit t('settings.form.submit_update')
  
    .block.left.relative
      = f.label :avatar do
        .avatar.big
          = image_tag @user.avatar.url('big_thumb'), id: 'avatar', class: 'avatar big'
        .button= 'Upload Image'
      - if is_owner
        = f.file_field :avatar, 'data-updatable' => true, class: 'hidden'
        = f.hidden_field :crop_coords, id: 'cropCoords'
        = f.hidden_field :avatar_cache
      - if is_owner && 
        #cropMenu{class: (@user.avatar_cache ? 'menu active' : 'menu')}
          = image_tag @user.avatar.url, id: 'jcrop'
          .inlineWrapper<
            = f.submit t('form.action.cancel'), name: 'cancel'
            = f.submit t('form.action.crop')
  
    = f.submit t('form.preview'), name: 'preview', class: 'hidden'
  .clearFix

app/views/users/edit.js.haml
$('#currentUser').attr('src','#{@user.avatar.url}').width('48px').height('48px');
- if params[:cancel]
  $('#user_avatar, #user_avatar_cache').val('');
  $('#cropMenu').removeClass('active');
- else
  $('#user_avatar').val('');
  $('#user_avatar_cache').val('#{j @user.avatar_cache}');
  JcropAPI = $('#jcrop').data('Jcrop');
  JcropAPI.destroy();
  $('#jcrop').attr('src',"#{j(@user.avatar.url + '?' + Time.now.to_s)}").width('').height('');
  $('#cropMenu').addClass('active');

app/views/users/get_invite.js.haml
- if @invite
  $('#invites').append('#{j(content_tag 'li', content_tag('span', @invite, class: 'selectable')).html_safe}');

app/views/users/index.html.haml
= @users.size
- @users.each do |user|
  %br
  = link_to (image_tag user.avatar.url('thumb'), class: 'avatar tiny') + user.name, user 
  - if user.logged_in?
    %b *
  

app/views/users/new.html.haml
= render 'form'

app/views/users/show.html.haml
.main<
  .idBlock.user.botomUp
    = image_tag @user.avatar.url('big_thumb'), class: 'left avatar big'
    .info
      %h1= @user.name
      - if is_owner
        .iconArray
          = link_to 'Log out', user_session_path, method: :delete
          = link_to 'Edit', edit_user_path(@user)
      - elsif current_user
        .iconArray
          - if current_user && @user.followers.map(&:id).include?(current_user.id)
            = link_to 'Unfollow', following_path(user_id: @user.id), method: :delete
          - else
            = link_to 'Follow', following_path(user_id: @user.id), method: :post
  %p#about.clearFix= @user.about
  #userStats<
    = link_to nil, class: 'wide25 inline noDecor' do
      %h4.textLike.smallMargin Entries
      %p.notable 0
    = link_to user_box_path(@user,'collection'), class: 'wide25 inline noDecor' do
      %h4.textLike.smallMargin Collection
      %p.notable= @user.boxes.find_by(slug: 'collection').box_items.count
    = link_to '', class: 'wide25 inline noDecor' do
      %h4.textLike.smallMargin Followers
      %p.notable= @user.follower_count
    = link_to '', class: 'wide25 inline noDecor' do
      %h4.textLike.smallMargin Following
      %p.notable= @user.followee_count
  %section.block.left
    - if is_owner
      #events
        %h3= t 'user.headers.events'
        %ul
          - @events.each do |e|
            %li
              - if e.author
                = link_to e.author, user_path(e.author)
              = t 'user.event.' + e.event_type
              = link_to_event e
      #quests   
        %h3= t 'user.headers.quests'
      %h3
        = t 'user.headers.invites'
        - if current_user.name == 'bobin' || current_user.name == 'Kirsty'
          = link_to get_invite_path, class: 'relative tipped', method: 'post', remote: true do
            .tooltip.tippedR.noWrap
              .tip
              %span= t 'tooltip.add_invite'
            %svg.icon.button.inline.roundButton.previewButton
              <use xlink:href=#plus />
      %ul#invites
        - (invites = @user.invites).each do |invite|
          %li
            - if invite.used_by
              - user = User.find(invite.used_by)
              %span.inactive= invite.word
              = link_to (image_tag user.avatar.url('thumb'), class: 'avatar tiny') + user.name, user
            -else
              %span.selectable= invite.word
  %section.block.left
    #lists
      = render 'lists'
  .clearFix

app/views/users/vote.js.haml
- if @polish
  $('#rating').text('#{@polish.rating.round(1)}');
  $('#votesCount').text(#{@polish.votes_count});
- if @comment
  var voteBox = $('.comment[data-id=#{@comment.id}]').find('.vote');
  voteBox.text('#{@comment.rating > 0 ? "+#{@comment.rating}" : @comment.rating}');
  - if @comment.rating > 0 
    voteBox.removeClass('negative').addClass('positive');
  - elsif @comment.rating < 0
    voteBox.removeClass('positive').addClass('negative');
  - else
    voteBox.removeClass('positive negative');