config/routes.rb
Rails.application.routes.draw do
  
  match '/', to: 'page#index', via: [:get, :post], as: 'root'

  resources :comments, only: [:create, :update, :destroy], path: 'comment'
  
  post 'lab/:brand_id/:polish_id/rollback/:version_id', to: 'polishes#rollback', as: 'brand_polish_rollback'
  post 'vote/:votable_type/:votable_id', to: 'users#vote', as: 'vote'
  post 'note/:polish_id', to: 'polishes#note', as: 'note'
  post 'collect/:polish_id', to: 'polishes#collect', as: 'collect'
  post 'lock/:polish_id', to: 'polishes#lock', as: 'lock'
  post 'get_invite', to: 'users#get_invite'
  post 'switch/:switch/:option', to: 'user_sessions#switch', as: 'switch'
  patch 'boxes/:id', to: 'boxes#update', as: 'update_box'
  post ':user_id/download/:id', to: 'boxes#export', as: 'download_box'
  get 'find_related', to: 'polishes#find_related'
  get 'search', to: 'application#search'
  get 'lab_search', to: 'application#lab_search'
  match 'collection_search', to: 'application#collection_search', via: [:get, :post]
  match 'collect_search', to: 'application#collect_search', via: [:get, :post]
  get 'reorder', to: 'polishes#reorder'
  get 'autocomplete', to: 'application#autocomplete'
  get 'bottling_status/:id', to: 'polishes#get_bottling_status', as: 'get_bottling_status'
  get 'lab/maintenance', to: 'page#maintenance'
  get 'lab/bottle_list', to: 'bottles#index'
  get 'lab/user_list', to: 'users#index'
  match 'catalogue/colour_search', to: 'polishes#colour_search', as: 'colour_search', via: [:get, :post]

  resources :ads

  scope '/catalogue' do
    get '/', to: 'polishes#index', as: 'catalogue'
    constraints(id: /[^\/]+/) do
      get ':brand_id', to: 'brands#show', as: 'catalogue_brand'
      get ':brand_id/:polish_id', to: 'polishes#show', as: 'catalogue_brand_polish'
    end
  end
  
  scope '/lab' do
    constraints(id: /[^\/]+/) do
      resources :brands    , lab: 'true', param: 'brand_id', path: '' 
      resources :brands    , lab: 'true', only: [], path: '' do
        resources :polishes, lab: 'true', except: :index, param: 'polish_id', path: ''
        resources :polishes, lab: 'true', only: [], param: 'polish_id', path: '' do
          get :redress     , lab: 'true', on: :member
          get 'versions'   , lab: 'true', to: 'polish_versions#index', on: :member
          post :clone, on: :member
        end
        resources :bottles , lab: 'true', except: :index
      end
    end
  end

  resource :user_session, only: [:create, :destroy]
  resource :following, only: [:create, :destroy]
  
  constraints(id: /[^\/]+/) do
    resources :users, param: 'user_id', except: [:index, :create, :new], path: '' do
      get 'tags/:tag', to: 'entries#index', as: 'tag', on: :member
    end
    resources :users, path: '', only: [] do
      resources :boxes, except: [:index, :edit], path: '' do
        post :import, on: :member
        post :clear, on: :member
        get :gather, on: :member
        get :edit, on: :member, to: 'boxes#show', edit: true
      end
      resources :followings, only: [:create, :destroy]
      resources :entries, path: 'diary' do
        post :like, on: :member          
      end    
    end
  end  
  
end

app/models/box.rb
# encoding: utf-8
class Box < ActiveRecord::Base
  include Slugify, ColourMethods

  before_validation :name_to_slug
  
  belongs_to :user
  has_many :box_items, dependent: :destroy
  has_many :polishes, through: :box_items
  
  validates :slug, uniqueness: {scope: :user_id, message: 'already exists for this user', :case_sensitive => false }, :allow_blank => false
  
  EXPORT_OPTIONS = {
    'csv' => {'colour' => true, 'note' => true, 'rating' => true},
    'xlsx' => {'colour' => true, 'bottle' => false, 'nail' => false, 'note' => true, 'rating' => true},
    'image' => {'bottle' => true, 'nail' => false, 'note' => true, 'rating' => false, 'bg_colour' => '#fff', 'columns' => 7}
  }

  def import(file)
    spreadsheet = Roo::Spreadsheet.open(file.path, extension: File.extname(file.path))
    header = self.rename_header_columns(spreadsheet.row(1))
    brand_i = header.index('brand') + 1
    name_i = header.index('polish') + 1
    number_i = header.index('number') + 1 if header.include?('number')
    collection_i = header.index('collection') + 1 if header.include?('collection')
    year_i = header.index('year') + 1 if header.include?('year')
    items = self.box_items
    stats = {total: 0, added: 0, new: 0, failed: 0, unknown: Set.new}
    brands = Set.new
    (2..spreadsheet.last_row).each do |i|
      # row = Hash[[header, spreadsheet.row(i)].transpose]
      
      unless spreadsheet.cell(i,brand_i).blank?
        brand_name = (is_numeric?(spreadsheet,i,brand_i) ? spreadsheet.excelx_value(i,brand_i) : spreadsheet.cell(i,brand_i)).to_s.squish.strip.gsub(/\.0$/, '')
        ids = Synonym.where("name ilike ? AND word_type = 'Brand'", "#{brand_name}%").pluck('word_id')
        brand = Brand.find(ids.first) unless ids.empty?
        if brand
          if is_numeric?(spreadsheet,i,name_i)
            number = spreadsheet.excelx_value(i,name_i).to_s
          else
            name = spreadsheet.cell(i,name_i).to_s
          end
          unless spreadsheet.excelx_type(i,number_i).blank?
            number = (is_numeric?(spreadsheet,i,number_i) ? spreadsheet.excelx_value(i,number_i) : spreadsheet.cell(i,number_i)).to_s
          end
          collection = (is_numeric?(spreadsheet,i,collection_i) ? spreadsheet.excelx_value(i,collection_i) : spreadsheet.cell(i,collection_i)).to_s
          year = (is_numeric?(spreadsheet,i,year_i) ? spreadsheet.excelx_value(i,year_i) : spreadsheet.cell(i,year_i)).to_s
          polish = Polish.find_brand_polishes(brand, name).first
          polish ||= Polish.new
          if polish.new_record?
            polish.draft = true
            unless name.blank?
              polish.name = name 
              polish.synonyms.new(name: name)
            end
            polish.number = number.gsub(/\.0$/, '') unless number.blank? || number.mb_chars.downcase == 'n/a'
            polish.collection = collection unless collection.blank?
            polish.release_year = year if !year.blank? 
            polish.brand_id = brand.id
            polish.brand_name = brand.name
            polish.brand_slug = brand.slug
            polish.user_id = self.user_id
            puts polish.inspect
            polish.save
            stats[:new] += 1
            brands << brand
          elsif (polish.collection.blank? && !collection.blank?) || ((polish.release_year.blank? || polish.release_year == 0) && !year.blank?)
            polish.collection = collection unless collection.blank?
            polish.release_year = year unless year.blank? || year == '0'
            polish.save
          end
        else
          stats[:failed] += 1
          stats[:unknown] << brand_name
        end
        if polish && polish.id
          unless items.find_by_polish_id(polish.id)
            self.box_items.new(polish_id: polish.id).save
            stats[:added] += 1
          end
          stats[:total] += 1
        end
      end
    end
    stats[:unknown] = stats[:unknown].to_a[0..-2].join(', ') + ' and ' + stats[:unknown].to_a.last if stats[:unknown].size >= 2
    self.import_result = "#{stats[:total]};#{stats[:added]};#{stats[:new]};#{stats[:failed]};#{stats[:unknown] unless stats[:unknown].blank?}"
    self.save
    for b in brands
      b.drafts_count = b.polishes.where(draft: true).count
      b.save
    end
    return stats
  end
  
  def export_image collection, bg = 'transparent', columns = 4, note = false, bottle = false, nail = false, rating = false
    path = Rails.root.join('public').to_s
    output_folder = "/downloads/#{self.user_id}"
    FileUtils.mkdir_p(path + output_folder) unless File.directory?(path + output_folder)    
    row_items = []
    rows = []
    stack = ''
    (polishes = collection).each_with_index do |polish,index|
      row_items << polish
      if ((index + 1).modulo(columns) == 0 ) || index == (polishes.size - 1)
        row_items.reverse.each_with_index do |p,i|
          p.brand_name
          if bottle && nail
            stack += " \\( #{path + (p.draft ? '/assets/draft.png' : p.bottle_url)} -geometry +#{(row_items.size - i - 1) * 360}+30 \\) -composite "
            stack += " \\( #{path + '/assets/preview_shadow.png'} -geometry 145x290+#{(row_items.size - i - 1) * 360 + 210}+112 \\) -composite "
            stack += " \\( #{path + p.preview_url} -geometry 155x290+#{(row_items.size - i - 1) * 360 + 205}+112 \\) -composite " unless p.draft
            if note
              stack += name_string(310, p, 360, 407, 35, row_items.size - i)
            else
              stack += name_string(310, p, 360, 407, 35, row_items.size - i)
              # stack += " #{path}"
            end
          elsif bottle
            stack += " \\( #{path + (p.draft ? '/assets/draft.png' : p.bottle_url)} -geometry +#{(row_items.size - i - 1) * 250}+#{p.draft ? 92 : 0} \\) -composite "
            if note
              stack += name_string(240, p, 250, 377, 5, row_items.size - i)
            else
              stack += name_string(240, p, 250, 377, 5, row_items.size - i)
            end
          elsif nail
            stack += " \\( #{path + '/assets/preview_shadow.png'} -geometry 186x372+#{(row_items.size - i - 1) * 250 + 28}+60 \\) -composite "
            stack += " \\( #{path + p.preview_url} -geometry +#{(row_items.size - i - 1) * 250 + 22}+60 \\) -composite " unless p.draft
            if note
              stack += name_string(240, p, 250, 442, 1, row_items.size - i)
            else
              stack += name_string(240, p, 250, 442, 1, row_items.size - i)
            end
          else

          end
        end
        row = "row_#{(index / columns ).to_i}.png"
        rows << row
        if bottle && nail
          Magick.convert " -size #{columns * 360}x590 canvas:transparent ", stack, output_folder + '/' + row
        elsif bottle
          Magick.convert " -size #{columns * 250}x590 canvas:transparent ", stack, output_folder + '/' + row
        elsif nail
          Magick.convert " -size #{columns * 250}x590 canvas:transparent ", stack, output_folder + '/' + row
        else
          
        end

        stack = ''
        row_items = []
      elsif index.modulo(columns) != 0
      end
    end
    stack = ''
    rows.each_with_index do |row,i|
      if !bottle && nail
        stack += " #{path + output_folder}/#{row} -geometry +10+#{i * 525} -composite "
      else
        stack += " #{path + output_folder}/#{row} -geometry +10+#{i * 430} -composite "
      end
    end
    if bottle && nail
      Magick.convert "-size #{columns * 360 + 50}x#{rows.size * 430 + 130} canvas:'#{bg}'", stack, output_folder + '/' + self.slug + '.png'
    elsif bottle
      Magick.convert "-size #{columns * 250}x#{rows.size * 430 + 130} canvas:'#{bg}'", stack, output_folder + '/' + self.slug + '.png'
    elsif nail
      Magick.convert "-size #{columns * 250 + 10}x#{rows.size * 525 + 130} canvas:'#{bg}'", stack, output_folder + '/' + self.slug + '.png'
    else
      
    end
  end
  
  def export_csv colour = true, bottle = false, nail = false, note = true, rating = true, user_id
    CSV.generate do |csv|
      headers = %w(brand name colour rating notes).map{|h| I18n.t('sheet.' + h)}
      csv << headers
      self.polishes.each do |p|
        name_or_number = !p.name.blank? ? !p.number.blank? ? (p.name + ' - ' + p.number) : p.name : p.number 
        colour = get_colour_names([p.h,p.s,p.l]).last
        csv << [p.brand_name, name_or_number, colour]
      end
    end
  end
  
  def export_xlsx colour = true, bottle = false, nail = false, note = true, rating = true, user_id
    path = Rails.root.join('public').to_s
    output_folder = "/downloads/#{self.user_id}"
    FileUtils.mkdir_p(path + output_folder) unless File.directory?(path + output_folder)    
    headers = ['brand', 'name','collection', 'year', 'colour', 'rating', 'notes'].map{|h| I18n.t('sheet.' + h)}
    package = Axlsx::Package.new
    package.workbook.add_worksheet(:name => self.user.slug + '_' + self.slug) do |sheet|
      heading = sheet.styles.add_style(alignment: {horizontal: :center, vertical: :center}, b: true, sz: 14, bg_color: 'A4C03C', fg_color: 'FFFFFF')
      sheet.add_row headers, style: heading, height: 20
      color_cell_styles = []
      self.polishes.each_with_index do |p,i|
        name_or_number = p.name_and_number
        colour_name = get_colour_names([p.h,p.s,p.l]).last
        fg_colour = (p.l.blank? || p.l > 50) ? '000000' : 'FFFFFF' 
        link = 'http://i-n-p-d.com/catalogue/' + p.brand_slug + '/' + p.slug
        img = path + (p.draft ? '/assets/' : '') + p.bottle_url('thumb')
        if p.h
          color_cell_styles << sheet.styles.add_style(bg_color: hsl_to_rgbhex(p.h,p.s,p.l), fg_color: fg_colour, alignment: {horizontal: :center})
          sheet.add_row [p.brand_name, name_or_number, p.collection, p.release_year, colour_name], style: [nil, nil, nil, nil, color_cell_styles.last], types: :string
        else
          sheet.add_row [p.brand_name, name_or_number, colour_name]
        end

app/controllers/boxes_controller.rb
class BoxesController < ApplicationController
  include Slugify
  
  def show
    set_user
    @load_colour_picker = current_user && current_user == @user
    cookies[:box_sort] ||= 'slug'
    set_box
    set_user_votes
  end
  
  def gather
    set_user
    set_box
    @addable = if @polishes.size > 0
      Polish.where('id NOT IN (?)', @box.polishes.pluck(:id))
    else
      Polish.where(nil)
    end.order('created_at ASC').page(params[:page_b]).per(12)
    render :show
  end
  
  def clear
    set_user
    set_box
    if @box.user_id == current_user.id
      @box.box_items.each &:destroy
    end
    render :show
  end
  
  def import
    @box = current_user.boxes.find_by_slug(params[:id])
    @box.import(params[:spreadsheet])
    @polishes = @box.polishes
  end
  
  def export
    set_user
    set_box
    case params[:button]
    when 'csv'
      send_data @box.export_csv(params[:colour], params[:bottle], params[:nail], params[:note], params[:rating], current_user.id), filename: @box.name + '.csv' and return
    when 'xlsx'
      @box.export_xlsx params[:colour], params[:bottle], params[:nail], params[:note], params[:rating], current_user.id
      # render plain: 'lalala'
      send_file Rails.root.join('public').to_s + "/downloads/#{@box.user_id}/#{@box.slug}.xlsx", type: "application/vnd.ms-excel" and return
    when 'image'
      # @box.export_image
      # send_file '/out.png', type: 'image/png', disposition: 'inline'
      columns = params[:columns].to_i
      columns = 9 if columns > 9 
      columns = 1 if columns < 1
      @box.export_image(@polishes, params[:bg_colour], columns, params[:note], params[:bottle], params[:nail], params[:rating])
      send_file Rails.root.join('public').to_s + "/downloads/#{@box.user_id}/#{@box.slug}.png", type: 'image/png', disposition: 'inline'
    end
  end
  
  def create
    if current_user && !params[:box].blank?
      box = Box.where(user_id: current_user.id, slug: slugify(params[:box])).first
      (@box = current_user.boxes.new(name: params[:box])).save unless box
    end
  end

  def update
    @box = Box.find(params[:id])
    @box.name = params[:box][:name]
    @box.save
  end
  
  def destroy
    set_user
    set_box
    if @box.user_id == current_user.id
      @box.destroy
    end
    redirect_to @user
  end
  
  private
  
  def set_box
    @box = @user.boxes.find_by_slug(params[:id])
    @polishes = @box.polishes.order(set_polish_sort)
    @brands = @polishes.pluck(:brand_id, :brand_name).uniq.sort{|a,b| a[1].mb_chars.downcase <=> b[1].mb_chars.downcase}
    @polishes = @polishes
    set_notes if @user == current_user
    @lists = @user.boxes    
  end
  
  def set_user
    @user = User.find_by_slug(params[:user_id])
  end
end

app/helpers/boxes_helper.rb
module BoxesHelper
  def brand_to_tag brand
    check_box_tag("filter_brand[#{brand[0]}]", nil, nil, class: '', 'data-updatable' => true) + label_tag("filter_brand[#{brand[0]}]",brand[1], class: 'tag')
  end
end

app/views/boxes/_box.html.haml
- user ||= current_user
= link_to user_box_path(user, box.slug), class: 'noDecor' do
  %span.linkLike= box.adapt_name
  %span.textLike.inactive= "(#{box.box_items.count})"

app/views/boxes/create.js.haml
$('#listForm').removeClass('active')
$('#box').val('');
- if @box
  $('#listForm').after('<li>#{j(render @box).html_safe}</li>');

app/views/boxes/import.js.haml
- result = @box.import_result.split(';')
- total = result[0]
- added = result[1]
- new = result[2]
- failed = result[3]
- missing_brands = result[4]
- if @polishes
  $('#secondaryResults').html('#{j(render @polishes, big_polish: true).html_safe}');
- if failed.to_i > 0
  $('#secondaryResults').prepend('#{content_tag :p, t('user.import_msg.added', count: added) + t('user.import_msg.failed', count: failed) + t('user.import_msg.unknown', count: missing_brands.size, brands: missing_brands)}');
- else
  $('#secondaryResults').prepend('#{content_tag :p, t('user.import_msg.ok', count: added)}');

app/views/boxes/show.html.haml
.main
  #List.block.left.relative<
    = text_field_tag 'box[name]', @box.name, placeholder: 'List Name', id:'boxNameField',style: ('display:none' if !params[:edit] || %(collection wishlist giveaway).include?(@box.slug) ), class: 'formIndent bigMargin smallMargin', 'data-id' => @box.id
    %h1#boxName.smallMargin{style: ('display:none' if params[:edit] && !%(collection wishlist giveaway).include?(@box.slug) )}<
      %span<= @box.adapt_name
      - if is_owner
        = link_to gather_user_box_path(@user, @box), style: ('display:none' if params[:edit]), class: 'relative tipped', remote: true do
          .tooltip.tippedR.noWrap
            .tip
            %span= t 'tooltip.add_polish'
          %svg.icon.button.inline.roundButton.previewButton
            <use xlink:href=#plus />
    - if is_owner
      = form_tag import_user_box_path(@user, @box), id: 'controls', class: 'controls', multipart: true do
        = label_tag :spreadsheet, t('user.import')
        = file_field_tag :spreadsheet, class: 'hidden', 'data-updatable' => true
        = submit_tag 'import', class: 'hidden', name: 'preview'
        %span.switch{'data-activate' => '#exportMenu'}>= t('user.export')
        %span#doneEditing.active{style: ('display:none' unless params[:edit])}>= link_to t('form.done_editing'), user_box_path(@user, @box, done_editing: true), remote: true
        %span#goEdit{style: ('display:none' if params[:edit])}>= link_to t('form.edit'), edit_user_box_path(@user, @box), remote: true
      = form_tag download_box_path(@user, @box) do
        - setup = Box::EXPORT_OPTIONS
        - type = params[:export] || 'xlsx'
        %ul#exportMenu{class: params[:export] ? 'menu formed active' : 'menu formed'}
          %li.current.formed= t('user.export_setup')
          %li.controls.noMargin
            %span{class: ('active' if type == 'xlsx')}= link_to 'XLSX', export: 'xlsx'
            %span{class: ('active' if type == 'csv')}= link_to 'CSV', export: 'csv'
            %span{class: ('active' if type == 'image')}= link_to 'Image', export: 'image'
          %li.switchHolder <svg class='icon linkLike switch' data-activate='#exportMenu'><use xlink:href='#x'/></svg>
          - %w(colour bottle nail rating note).each do |e|
            - if setup[type].keys.include? e
              %li.notCurrent
                %label{for: e}
                  = t 'controls.include_' + e
                  = check_box_tag e, 'yes', setup[type][e], class: 'hidden'
                  .checkBox{for: e} <svg class='icon check'><use xlink:href='#check' /></svg>
          - if setup[type].keys.include? 'bg_colour'
            %li.notCurrent
              %label{for: 'colour'}= t 'controls.export_colour'
              = text_field_tag :bg_colour, setup[type]['bg_colour'], id: 'colour', class: 'colour inMenu'
          - if setup[type].keys.include? 'columns'
            %li.notCurrent
              %label{for: 'columns'}= t 'controls.export_columns'
              = number_field_tag :columns, setup[type]['columns'],  max: 9, min: 1
          %li.formLi
            = button_tag 'Download', value: (params[:export] || 'xlsx'), class: 'inline noWrap wide100'
              
    
    #secondarySearchResults<
    #secondaryResults<
      = render @polishes, big_polish: true, break_on_brand: cookies[:box_sort] == 'slug'
    - if is_owner    
      #gather{class: (params[:action] == 'gather' ? 'menu active' : 'menu' )}
        .current
          %span.header
            - if %(collection wishlist giveaway).include?(@box.slug)
              = t('user.list.' + @box.slug)
            - else
              = @box.name
        = link_to "<svg class='icon' data-activate='#boxesList'><use xlink:href='#x'/></svg>".html_safe, user_box_path(@user,@box.slug), class: 'switch wideAuto', remote: true
        .formLi.smallMargin= render 'search', setup: %w(brand polish), collect_search: true, css: 'wide100 autoupdatable', remote: true
        #searchResults<
        #results<
          - if params[:action] == 'gather'
            = render @addable, add: true
    
  %section#Catalogue.block.left
    .formIndent
      = render 'search', setup: ['polish'], css: 'bigMargin wide100 autoupdatable', collection_search: true, id: 'secondarySearch', remote: true
  
    = form_tag collection_search_path(box_id: @box.id), remote: true do
      = hidden_field_tag :polish, params[:polish], id: 'filterPolish'
  
      %h3= t 'user.headers.sort'
      #sort.controls.bottomMargin<
        - cookies[:box_sort] ||= 'time'
        - %w(slug rating colour created_at).each do |c|
          - if cookies[:box_sort] == c
            %span.active= t('controls.by_' + c)
          - else
            = label_tag 'box_sort_' + c, t('controls.by_' + c)
          = submit_tag c, name: 'box_sort', id: 'box_sort_' + c, class: 'hidden'
        
      %h3= t 'user.headers.brands'
      #tags.tags.bottomMargin<
        - @brands.each do |brand|
          = brand_to_tag(brand)
      = submit_tag nil, name: 'preview', class: 'hidden', id: 'submitFilterBrands'
      
    = render 'lists'
    ToDo: design 
    = link_to 'clear list', clear_user_box_path(@user,@box), method: :post
    and 
    = link_to 'destroy', user_box_path(@user,@box), method: :delete
    buttons
  .clearFix
  

app/views/boxes/show.js.haml
- if params[:action] == 'gather'
  - if @addable.size > 0
    $('#results').html('#{j(render(@addable, add: true).html_safe)}');
  $('#gather').addClass('active');
  history.pushState({}, '', '/#{params[:user_id]}/#{params[:id]}/gather');
- elsif params[:edit]
  var collection = $('.bigPolish');
  collection.find('.roundButton').show();
  collection.each(function() {
  var id = $(this).data('id');
  $(this).children('a').attr('href', '/collect/' + id + '?box=#{@box.slug}&from_list=true').attr('data-method','post').attr('rel','nofollow').attr('data-remote','true')
  });
  $('#goEdit').hide();
  $('#doneEditing').show();
  - if %(collection wishlist giveaway).include?(@box.slug)
    $('h1').find('a').hide();
  - else 
    $('h1').hide();
    $('#boxNameField').show().focus();
  history.pushState({}, '', '/#{params[:user_id]}/#{params[:id]}/edit');
- else
  - if @polishes.size > 0
    $('#secondaryResults').find('svg.roundButton').hide()
    var collection = $('.bigPolish');
    collection.each(function() {
    var link = $(this).find('.info').find('a').attr('href')
    $(this).children('a').attr('href', link).removeAttr('data-method').removeAttr('rel').removeAttr('data-remote')
    });
  if ( $('#tags').find('label').size() != #{@brands.size}) {
  var activeBrands = 0;
  $('#tags').html('');
  - @brands.each do |brand|
    $('#tags').append('#{j(brand_to_tag(brand)).html_safe}');
    if ($('#filterBrand').find('input[name="filter_brand[#{brand[0]}]"]').size() > 0) {
    $('#tags').find('input[name="filter_brand[#{brand[0]}]"]').prop('checked', true);
    activeBrands += 1;
    }    
  $('#tags').find('input[data-updatable=true]').on('change', function() {
  $('#submitFilterBrands').click();
  });
  if (activeBrands > 0 || $('#filterBrand').find('input').size() != activeBrands) {
  $('#submitFilterBrands').click();
  }
  }
  $('#goEdit').show();
  $('#doneEditing').hide();
  $('#gather').removeClass('active');
  $('h1').show();
  $('h1').find('a').show();
  $('#boxNameField').hide();
  history.pushState({}, '', '/#{params[:user_id]}/#{params[:id]}');

app/views/boxes/update.js.haml
$('#doneEditing').children('a').attr('href','/#{current_user.slug}/#{@box.slug}');
var goGather = $('#boxName').find('a');
$('#goEdit').children('a').attr('href','/#{current_user.slug}/#{@box.slug}/edit');
$('h1').html('#{@box.name}').append(goGather.attr('href','/#{current_user.slug}/#{@box.slug}/gather'));
- unless %(collection wishlist giveaway).include?(@box.slug)
  $('#gather').find('.header').text('#{@box.name}');
$('#gather').find('.switch').attr('href','/#{current_user.slug}/#{@box.slug}');
$('.bigPolish').each(function() {$(this).find('a').attr('href','/collect/' + $(this).data('id') + '?box=#{@box.slug}&from_list=true');});