config/routes.rb
Rails.application.routes.draw do
  
  match '/', to: 'page#index', via: [:get, :post], as: 'root'

  resources :comments, only: [:create, :update, :destroy], path: 'comment'
  
  post 'lab/:brand_id/:polish_id/rollback/:version_id', to: 'polishes#rollback', as: 'brand_polish_rollback'
  post 'vote/:votable_type/:votable_id', to: 'users#vote', as: 'vote'
  post 'note/:polish_id', to: 'polishes#note', as: 'note'
  post 'collect/:polish_id', to: 'polishes#collect', as: 'collect'
  post 'lock/:polish_id', to: 'polishes#lock', as: 'lock'
  post 'get_invite', to: 'users#get_invite'
  post 'switch/:switch/:option', to: 'user_sessions#switch', as: 'switch'
  patch 'boxes/:id', to: 'boxes#update', as: 'update_box'
  post ':user_id/download/:id', to: 'boxes#export', as: 'download_box'
  get 'find_related', to: 'polishes#find_related'
  get 'search', to: 'application#search'
  get 'lab_search', to: 'application#lab_search'
  match 'collection_search', to: 'application#collection_search', via: [:get, :post]
  match 'collect_search', to: 'application#collect_search', via: [:get, :post]
  get 'reorder', to: 'polishes#reorder'
  get 'autocomplete', to: 'application#autocomplete'
  get 'bottling_status/:id', to: 'polishes#get_bottling_status', as: 'get_bottling_status'
  get 'lab/maintenance', to: 'page#maintenance'
  get 'lab/bottle_list', to: 'bottles#index'
  get 'lab/user_list', to: 'users#index'
  match 'catalogue/colour_search', to: 'polishes#colour_search', as: 'colour_search', via: [:get, :post]

  resources :ads

  scope '/catalogue' do
    get '/', to: 'polishes#index', as: 'catalogue'
    constraints(id: /[^\/]+/) do
      get ':brand_id', to: 'brands#show', as: 'catalogue_brand'
      get ':brand_id/:polish_id', to: 'polishes#show', as: 'catalogue_brand_polish'
    end
  end
  
  scope '/lab' do
    constraints(id: /[^\/]+/) do
      resources :brands    , lab: 'true', param: 'brand_id', path: '' 
      resources :brands    , lab: 'true', only: [], path: '' do
        resources :polishes, lab: 'true', except: :index, param: 'polish_id', path: ''
        resources :polishes, lab: 'true', only: [], param: 'polish_id', path: '' do
          get :redress     , lab: 'true', on: :member
          get 'versions'   , lab: 'true', to: 'polish_versions#index', on: :member
          post :clone, on: :member
        end
        resources :bottles , lab: 'true', except: :index
      end
    end
  end

  resource :user_session, only: [:create, :destroy]
  resource :following, only: [:create, :destroy]
  
  constraints(id: /[^\/]+/) do
    resources :users, param: 'user_id', except: [:index, :create, :new], path: '' do
      get 'tags/:tag', to: 'entries#index', as: 'tag', on: :member
    end
    resources :users, path: '', only: [] do
      resources :boxes, except: [:index, :edit], path: '' do
        post :import, on: :member
        post :clear, on: :member
        get :gather, on: :member
        get :edit, on: :member, to: 'boxes#show', edit: true
      end
      resources :followings, only: [:create, :destroy]
      resources :entries, path: 'diary' do
        post :like, on: :member          
      end    
    end
  end  
  
end

app/models/brand.rb
class Brand < ActiveRecord::Base
  include Slugify
  
  before_validation :name_to_slug

  validates :slug, uniqueness: true, presence: true
  
  has_many :collections,         dependent: :destroy
  has_many :polishes,            dependent: :destroy
  has_many :bottles,             dependent: :destroy
  has_many :synonyms, as: :word, dependent: :destroy

  def synonym_list; self.synonyms.map(&:name).try(:join, '; ')  end
  def synonym_list=(names)    
    self.synonyms = names.split(';').map{|n| Synonym.where(word_type: 'Brand', word_id: self.id, name: n.strip).first_or_create!} 
  end 
  
  def folder; "/assets/brands/#{self.slug}" end
  
  scope :sort_by_polishes_count, -> { order(polishes_count: :DESC, name: :ASC) }

  def to_param; slug end
  
  def name_to_slug
    unless self.name.squish!.empty?
      self.slug = slugify(self.name)
    end
  end  
  
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  def index
    Brand.new(name: 'Default', user_id: current_user.id).save if Brand.count == 0
    @brands = Brand.all.sort_by_polishes_count.page(params[:page]).per(10)
  end

  def show
    set_brand    
    set_bottles
    in_lab? ? lab_search : search
    @polishes = @polishes.page(params[:page]).per(Defaults::PER[:lab_polishes])
    render 'catalogue_show' if !in_lab?
  end

  def new
    @brand = Brand.new
  end

  def edit
    set_brand
    set_bottles
  end

  def create
    @brand = Brand.new(brand_params)
    set_name
    @brand.user_id = current_user.id

    respond_to do |format|
      if @brand.save
        format.html { redirect_to brand_path(@brand), notice: 'Brand was successfully created.' }
        format.json { render :show, status: :created, location: @brand }
      else
        format.html { render :new }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    set_brand
    set_name
    respond_to do |format|
      if @brand.update(brand_params)
        format.html { redirect_to brand_path(@brand), notice: 'Brand was successfully updated.' }
        format.json { render :show, status: :ok, location: @brand }
      else
        format.html { render :edit }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    set_brand
    FileUtils.rm_rf(path + @brand.folder)
    @brand.destroy
    respond_to do |format|
      format.html { redirect_to brands_url, notice: 'Brand was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_name
    @brand.name = params[:brand][:synonym_list].split(';')[0].try(:strip)
  end

  def brand_params
    params.require(:brand).permit(:synonym_list, :link)
  end
end

app/views/brands/_brand.html.haml
%tr
  %td.wide100
    = link_to brand.name, brand
  - if current_user && current_user.slug == 'bobin'
    %td.noWrap.iconArray<
      = link_to "<svg class='icon hoverBack'><use xlink:href='#pencil' /></svg>".html_safe, edit_brand_path(brand)
      = link_to "<svg class='icon hoverBack'><use xlink:href='#trash' /></svg>".html_safe, brand, method: :delete, data: { confirm: t('form.confirm') }
  - else
    %td.noWrap.iconArray<
      <svg class='icon hoverBack'><use xlink:href='#pencil' /></svg><svg class='icon hoverBack'><use xlink:href='#trash' /></svg>

app/views/brands/_form.html.haml
= form_for @brand, html: {class: 'columnForm'} do |f|
  - if @brand.errors.any?
    #error_explanation
      %h3= "#{pluralize(@brand.errors.count, "error")} prohibited this brand from being saved:"
      %ul
        - @brand.errors.full_messages.each do |msg|
          %li= msg
          
  = f.text_field :synonym_list, placeholder: t('placeholder.synonym'), autofocus: 'autofocus'
  = f.text_field :link, placeholder: t('placeholder.link')
  = f.submit t('form.save'), class: 'wide100'

app/views/brands/_show.html.haml
#listing.block.left
  %h2
    = link_to_if (params[:controller] != 'brands' || params[:action] != 'show'),  @brand.name, @brand
    - unless %w(new edit).include?(params[:action]) || !current_user
      = link_to new_brand_polish_path(@brand), class: 'tipped relative' do
        .tooltip.tippedR.noWrap
          .tip
          %span= t 'tooltip.new_polish', brand: @brand.name
        %svg.icon.button.inline.roundButton.previewButton
          <use xlink:href=#plus />
  = render 'search', setup: %w(polish), css: 'wide100 autoupdatable', lab_search: true, remote: true     
  #controls.controls.bigMargin
    - cookies[:lab_polish_filter] ||= 'all'
    - %w(all bottle draft).each do |f|
      %span{class: ('active' if cookies[:lab_polish_filter] == f)}
        = link_to_unless cookies[:lab_polish_filter] == f, t('controls.filter_' + f), switch_path('lab_polish_filter', f), method: 'post'

  #searchResults.wide100
  #results.wide100
    = render @polishes, no_vote: true

app/views/brands/catalogue_show.html.haml
.blockx2.left
  %h1.wide50.inline>= truncate (@brand.name), length: 50, separator: /_|-| /
  = render 'search', css: 'wide50 bigMargin completable', setup: %w(polish colour), remote: true
  - if @brand.link
    %h4.abovePolish= to_link @brand.link
  = render 'polishes/catalogue_search'
= render 'ads'

app/views/brands/edit.html.haml
%section#listing.left.block
  %h2= t('lab.edit') + ' ' + @brand.name
  = render 'form'

  = link_to 'Back', @brand
%section#action.left.block
  %h3.bigMargin
    = t('lab.new_polish_bottles')
  .array
    - @bottles.each do |bottle|
      .arrayItem{'data-bottle' => bottle.id}>
        - if bottle.brand_slug != @brand.slug
          .bottleThumbWrapper>= image_tag( bottle.base_thumb_url, class: 'bottleThumb img')
        - else
          .spotable.bottleThumbWrapper>
            = link_to brand_bottle_path(@brand, bottle), method: :delete, remote: true do
              =image_tag bottle.base_thumb_url, class: 'bottleThumb img'
              %svg.icon.button.roundButton.important
                <use xlink:href=#trash />
        = bottle.name

app/views/brands/index.html.haml
.main
  %section#listing.block
    %h2
      = t('lab.brands')
      = link_to new_brand_path, class: 'tipped relative' do
        .tooltip.tippedR.noWrap
          .tip
          %span= t 'tooltip.add_brand'
        %svg.icon.button.inline.roundButton.previewButton
          <use xlink:href=#plus />
    = render 'search', setup: %w(brand), css: 'wide100 autoupdatable', lab_search: true, remote: true
    
    %table#searchResults.wide100.hidden
    #results
      %table.wide100
        = render @brands
      = paginate @brands, window: 1, outer_window: 1

app/views/brands/new.html.haml
%section#listing.block
  %h2= t('lab.new_brand')

  = render 'form'

  = link_to 'Back', brands_path

app/views/brands/show.html.haml
.main
  = render 'show' 
  #action.left.block
    %h3.bigMargin
      = t('lab.new_polish_bottles')
      - if current_user
        = link_to new_brand_bottle_path(@brand), class: 'tipped relative' do
          .tooltip.tippedR.noWrap
            .tip
            %span= t 'tooltip.add_bottle'
          %svg.icon.button.inline.roundButton.previewButton
            <use xlink:href=#plus />
  
    .array
      - @bottles.each do |bottle|
        .arrayItem>
          .spotable.bottleThumbWrapper>= link_to_if current_user, (image_tag bottle.base_thumb_url, class: 'bottleThumb img'), new_brand_polish_path(@brand, bottle: bottle.id)
          = bottle.name
    - unless @brand.link.blank?
      = to_link @brand.link
      %br
    = t 'lab.polish_count', {total: @brand.polishes_count, drafts: @brand.drafts_count, unbottled: @brand.unbottled_count}
    %br      
    = link_to 'Edit', edit_brand_path(@brand)
    \|
    = link_to 'Back', brands_path 
  .clearFix
  
  
      