config/routes.rb
Rails.application.routes.draw do
  
  match '/', to: 'page#index', via: [:get, :post], as: 'root'

  resources :comments, only: [:create, :update, :destroy], path: 'comment'
  
  post 'lab/:brand_id/:polish_id/rollback/:version_id', to: 'polishes#rollback', as: 'brand_polish_rollback'
  post 'vote/:votable_type/:votable_id', to: 'users#vote', as: 'vote'
  post 'note/:polish_id', to: 'polishes#note', as: 'note'
  post 'collect/:polish_id', to: 'polishes#collect', as: 'collect'
  post 'lock/:polish_id', to: 'polishes#lock', as: 'lock'
  post 'get_invite', to: 'users#get_invite'
  post 'switch/:switch/:option', to: 'user_sessions#switch', as: 'switch'
  patch 'boxes/:id', to: 'boxes#update', as: 'update_box'
  post ':user_id/download/:id', to: 'boxes#export', as: 'download_box'
  get 'find_related', to: 'polishes#find_related'
  get 'search', to: 'application#search'
  get 'lab_search', to: 'application#lab_search'
  match 'collection_search', to: 'application#collection_search', via: [:get, :post]
  match 'collect_search', to: 'application#collect_search', via: [:get, :post]
  get 'reorder', to: 'polishes#reorder'
  get 'autocomplete', to: 'application#autocomplete'
  get 'bottling_status/:id', to: 'polishes#get_bottling_status', as: 'get_bottling_status'
  get 'lab/maintenance', to: 'page#maintenance'
  get 'lab/bottle_list', to: 'bottles#index'
  get 'lab/user_list', to: 'users#index'
  match 'catalogue/colour_search', to: 'polishes#colour_search', as: 'colour_search', via: [:get, :post]

  resources :ads

  scope '/catalogue' do
    get '/', to: 'polishes#index', as: 'catalogue'
    constraints(id: /[^\/]+/) do
      get ':brand_id', to: 'brands#show', as: 'catalogue_brand'
      get ':brand_id/:polish_id', to: 'polishes#show', as: 'catalogue_brand_polish'
    end
  end
  
  scope '/lab' do
    constraints(id: /[^\/]+/) do
      resources :brands    , lab: 'true', param: 'brand_id', path: '' 
      resources :brands    , lab: 'true', only: [], path: '' do
        resources :polishes, lab: 'true', except: :index, param: 'polish_id', path: ''
        resources :polishes, lab: 'true', only: [], param: 'polish_id', path: '' do
          get :redress     , lab: 'true', on: :member
          get 'versions'   , lab: 'true', to: 'polish_versions#index', on: :member
          post :clone, on: :member
        end
        resources :bottles , lab: 'true', except: :index
      end
    end
  end

  resource :user_session, only: [:create, :destroy]
  resource :following, only: [:create, :destroy]
  
  constraints(id: /[^\/]+/) do
    resources :users, param: 'user_id', except: [:index, :create, :new], path: '' do
      get 'tags/:tag', to: 'entries#index', as: 'tag', on: :member
    end
    resources :users, path: '', only: [] do
      resources :boxes, except: [:index, :edit], path: '' do
        post :import, on: :member
        post :clear, on: :member
        get :gather, on: :member
        get :edit, on: :member, to: 'boxes#show', edit: true
      end
      resources :followings, only: [:create, :destroy]
      resources :entries, path: 'diary' do
        post :like, on: :member          
      end    
    end
  end  
  
end

app/controllers/polishes_controller.rb
class PolishesController < ApplicationController
  include Slugify, ColourMethods, MagickMethods

  def index
    set_brand
    search
  end

  def show
    set_polish
    set_user_votes
    set_collections
    @synonyms = @polish.synonyms.to_a
    @synonyms.shift
    @comments = @polish.comments
    set_users @comments
    if !in_lab? && !@polish.draft
      @colour_names = get_colour_names([@polish.h,@polish.s,@polish.l])
      find_related @polish
      render 'catalogue_show'
    else
      @versions = @polish.versions
      @polishes = lab_search.page(params[:page]).per(Defaults::PER[:lab_polishes])
    end
  end
  
  def colour_search
    # `convert '/Users/fish/o.png' -resize 200x200^ -gravity center -crop 120x120+0+0 -colors 16 -depth 8 -colorspace HSL -format "%c" histogram:info:|sort -rn|head -16`
    @polish = Polish.new(polish_params)
    @load_colour_picker = true
    set_user_votes
    if @polish.reference?
      colours = Magick.convert @polish.reference.url, '-resize 200x200^ -gravity center -crop 150x150+0+0 -depth 8 -colors 24 -colorspace HSL -format "%c" histogram:info:|sort -rn', ''
      @debug = colours.to_s
      colours = colours.
        split("\n").
        map{|c| {count: /(\d+?)(?=:)/.match(c).to_s.to_i, h: /[\d\.]+(?=,[\d\.]+%)/.match(c).to_s.to_f, s: /[\d\.]*?(?=%)/.match(c).to_s.to_f, l: /[\d\.]*?(?=%\))/.match(c).to_s.to_f, hsl: /hsl\(.*?\)/.match(c).to_s}}.
        sort{ |x,y| y[:s] + y[:count] / 60 <=> x[:s] + x[:count] / 60 }
      @dominant_colours = merge_similar_colours colours
      nude_strict = Defaults::COLOURS[:tech]['nude_strict']
      nude_soft = Defaults::COLOURS[:tech]['nude_soft']
      nudes = []
      size = @dominant_colours.size - 1
      @dominant_colours.reverse.each_with_index do |colour, i|
        if (colour[:h].between?(nude_strict[:h].min,nude_strict[:h].max) && colour[:s].between?(nude_strict[:s].min,nude_strict[:s].max) && colour[:l].between?(nude_strict[:l].min,nude_strict[:l].max)) ||
          (colour[:count] > 4500 && colour[:h].between?(nude_soft[:h].min,nude_soft[:h].max) && colour[:s].between?(nude_soft[:s].min,nude_soft[:s].max) && colour[:l].between?(nude_soft[:l].min,nude_soft[:l].max))
          nudes << colour
          @dominant_colours.delete_at(size - i)
        end
      end
      @dominant_colours += nudes
    end
    cookies[:spread] = params[:spread].to_i if params[:spread]
    spread = spread || cookies[:spread] || 20
    @related = Polish.coloured(params[:colour], spread) unless params[:colour].blank?
    @colour = params[:colour].blank? ? @dominant_colours ? @dominant_colours.first[:hsl] : '' : colour_to_rgb(params[:colour])
  end
  
  def new
    set_brand
    set_bottles
    @load_colour_picker = true
    @polish = Polish.new
    @polish.bottle_id = params[:bottle] || Brand.find_by_slug('default').bottles.first.id
    @polish.user_id = current_user.id
    @polish.layers.new(layer_type: 'base')
    clear_tmp_folder
    all_layers_bottom_up
    @polishes = lab_search.page(params[:page]).per(Defaults::PER[:lab_polishes])
  end

  def edit
    set_polish
    set_bottles
    @load_colour_picker = true
    clear_tmp_folder
    @polish.bottle_id ||= Brand.find_by_slug('default').bottles.first.id
    @polish.user_id = current_user.id
    @polishes = lab_search.page(params[:page]).per(Defaults::PER[:lab_polishes])
    @polish.layers.new(layer_type: 'base') if @polish.layers.size < 1
    @layers = @polish.layers.map(&:dup).reject{|l| !l.new_record?}.sort{|a,b| a.ordering <=> b.ordering}
    @polish.generate_preview @layers
  end
  
  def redress
    set_polish
    set_bottles
  end
  
  def rollback
    set_polish
    old_slug = @polish.slug
    old_owner = @polish.user_id
    version = PolishVersion.find(params[:version_id])
    @polish.assign_attributes YAML.load(version.polish)
    all_layers_bottom_up
    @polish.bottling_status = false
    rename_polish_files old_slug if old_slug != @polish.slug
    @polish.save_version("rollback;#{version.version}")
    @polish.user_id = current_user.id
    @polish.notify
    @polish.layers.each{|l| l.destroy unless @layers.map(&:id).include?(l.id) || l.new_record?}
    @polish.generate_preview @layers, params[:changes]
    @polish.save
    @polish.flatten_layers @layers
    # @polish.delay(queue: current_user.id).flatten_layers @layers
    redirect_to @brand, notice: 'Older version is restored' 
  end
  
  def collect
    unless params[:box].blank?
      collection = (@box = current_user.boxes.find_or_initialize_by slug: slugify(params[:box]) ).box_items
      if @box.new_record? 
        @box.name = params[:box]
        @box.save
        @box_is_new = true
      end
      if (item = collection.detect{|item| item.polish_id == params[:polish_id].to_i})
        item.destroy
        @is_in = false
      else
        (@item = BoxItem.new box_id: @box.id, polish_id: params[:polish_id]).save
        @is_in = true
      end
      if @is_in 
        @user_votes = current_user.votes.where(votable_type: 'Polish', votable_id: params[:polish_id])
        polishes = Polish.where('id NOT IN (?)', collection.map( &:polish_id)).first(12 * (params[:page_b] || 1).to_i + 1)
        @next_item = polishes.last if polishes.count > 12
        @added_item = Polish.find(@item.polish_id)
      end 
      
    end
  end

  def create
    set_brand
    set_bottles
    @polish = @brand.polishes.new(polish_params)
    @polish.brand_name = @brand.name
    @polish.brand_slug = @brand.slug
    @polish.user_id = current_user.id
    set_name
    set_crackle
    all_layers_bottom_up
    if params[:preview]
      @polish.generate_preview @layers, params[:changes]
      respond_to do |format|
        format.html {render :new}
        format.js {render 'preview'}
      end
    elsif @polish.valid?
      @polish.bottling_status = false
      @polish.save_version('create')
      @polish.generate_preview @layers, params[:changes]
      @polish.save
      # @polish.delay(queue: current_user.id).flatten_layers @layers
      @polish.flatten_layers @layers
      redirect_to @brand, notice: 'Polish was successfully created.' 
    else
      @polishes = @brand.polishes.order('created_at desc').page(params[:page]).per(12)
      render :new
    end
  end

  def update
    set_polish
    set_bottles
    old_bottle_id = @polish.bottle_id
    old_slug = @polish.slug
    old_owner = @polish.user_id
    @polish.assign_attributes polish_params
    set_name
    set_crackle
    @polish.brand_name = @brand.name
    @polish.brand_slug = @brand.slug
    all_layers_bottom_up
    if params[:preview]
      @polish.generate_preview @layers, params[:changes]
      respond_to do |format|
        format.html {render :edit}
        format.js {render 'preview'}
      end
    elsif @polish.valid?
      @polish.bottling_status = false
      rename_polish_files old_slug if old_slug != @polish.slug
      @polish.draft = params[:polish][:draft] == '1'
      @polish.save_version( params[:redress] ? 'redress' : 'update')
      @polish.user_id = current_user.id
      @polish.notify
      if params[:redress]
        if old_bottle_id != @polish.bottle_id
          @polish.generate_bottle(true) 
        else
          @polish.bottling_status = true
        end
        @polish.save
        redirect_to @brand, notice: 'Polish was successfully updated.' 
      else
        @polish.layers.each{|l| l.destroy unless @layers.map(&:id).include?(l.id) || l.new_record?}
        @polish.generate_preview @layers, params[:changes]
        @polish.save
        @polish.flatten_layers @layers
        # @polish.delay(queue: current_user.id).flatten_layers @layers
        redirect_to @brand, notice: 'Polish was successfully updated.' 
      end
    else
      render (params[:redress] ? :redress : :edit)
    end
  end
  
  def clone
    set_polish
    @copy = @polish.dup
    @copy.layers_count = 0
    case (copies = @brand.polishes.where('slug ~ ?', "#{@polish.slug}_copy\((\d*|)\)$")).size
    when 0
      @copy.name = @copy.name_or_number + '_copy'
    when 1
      @copy.name = @copy.name_or_number + '_copy(2)'
    else
      last = copies.
        sort{|a,b| a.slug.split('_copy(').last.to_i <=> b.slug.split('_copy(').last.to_i}.
        last.slug.split('_copy(').last.to_i
      @copy.name = @copy.name_or_number + "_copy#{(last + 1)}"
    end
    @copy.assign_attributes YAML.load( @polish.to_yaml )
    @copy.user_id = current_user.id
    @copy.save
    @copy.save_version('clone')
    rename_polish_files @polish.slug, @copy
    respond_to do |format|
      format.html { redirect_to @brand, notice: 'Polish was successfully cloned.' }
      format.js
    end
  end
  
  def lock
    @polish = Polish.find(params[:polish_id])
    @polish.lock = !@polish.lock
    @polish.save
    respond_to do |format|
      format.html { redirect_to :back }
      format.js
    end
  end
  
  def destroy
    set_polish
    @id = @polish.id
    @polish.destroy
    respond_to do |format|
      format.html { redirect_to @brand, notice: 'Polish was successfully destroyed.' }
      format.js
    end
  end
  
  def get_bottling_status
    @polish = Polish.find(params[:id])
    head 204, content_type: "text/html" unless @polish.bottling_status
  end
  
  def find_related polish = nil, spread = nil
    set_user_votes
    cookies[:spread] = params[:spread].to_i if params[:spread]
    @polish = polish 
    @polish ||= (Polish.find(params[:polish_id]) if (params[:polish_id]) && params[:polish_id] != 'null')
    spread = spread || cookies[:spread] || 20
    if @polish
      @related = Polish.
        coloured( [@polish.h, @polish.s, @polish.l, @polish.opacity], spread)
    elsif !params[:colour].blank?
      @related = Polish.coloured(params[:colour], spread) 
    end
  end
  
  def reorder
    params[:lab] = false
    search
  end
  
  def note
    note = Note.find_or_initialize_by(user_id: current_user.id, polish_id: params[:polish_id])
    if params[:body].try(:strip).blank?
      note.destroy
    else

app/helpers/polishes_helper.rb
module PolishesHelper
  def bottle_or_spinner image_url, is_bottled, html = {}
    if params[:spinner] != 'force' && is_bottled 
      image_tag image_url, class: html[:class]
    else
      image_tag 'spinner_b.svg', class: html[:class].to_s + ' getBottlingStatus'
    end
  end
  
  def link_to_add_layer(type, f)
    layer = PolishLayer.new(layer_type: type)
    id = layer.object_id
    fields = f.fields_for(:layers, layer, child_index: id) do |ff|
      render 'layer_fields', l: layer, l_f: ff, f: f, object_id: id
    end
    link = link_to '#', class: "add_layer", data: {id: id, fields: fields.gsub("\n", "").gsub("class='layer'","class='layer' style='display:none'")} do
      content_tag( 'span', '',  id: ('add' + type.capitalize)) + content_tag('label', t('lab.section.' + type))
    end
    return link.html_safe
  end
end

app/views/polishes/_catalogue_search.html.haml
- if params[:brand] || params[:polish] || params[:colour]
  #results{style: 'display:none'}
  #searchResults= render @polishes, big_polish: true, no_vote: true
- else
  #results= render @polishes, big_polish: true, no_vote: true
  #searchResults{style: 'display:none'}

app/views/polishes/_collections.html.haml
.iconArray.relative<
  - %w(collection wishlist giveaway).each do |name|
    =link_to collect_path(@polish.id, box: name), method: :post, remote: true, class: 'tipped' do
      .tooltip
        .tip
        = t 'tooltip.' + name
      %span{id: name + 'List'}>
      <svg class='icon isOk button roundButton check' #{"style='display:none'" unless current_user.boxes.find_by(slug: name).box_items.detect{|item| item.polish_id == @polish.id} }><use xlink:href='#check' /></svg>
  .switchWrapper.inline.tipped
    %ul#boxesList.menu.furlable.formed
      %li.current.formed= t('catalogue.titles.lists')
      - current_user.boxes.each do |box|
        - unless %w(collection wishlist giveaway).include? box.slug
          %li.notCurrent
            = link_to  collect_path(@polish.id, box: box.slug), id: box.slug + 'List', method: :post, remote: true do
              = box.name
              - is_in = box.box_items.detect{|item| item.polish_id == @polish.id}
              <svg class='icon isOk check' #{"style='visibility:hidden'" unless is_in}><use xlink:href='#check' /></svg>
              <svg class='icon isOk plus' #{"style='visibility:hidden'" if is_in}><use xlink:href='#plus' /></svg>
      %li.formLi        
        = form_tag collect_path(@polish.id), class: 'menuForms', remote: true do
          .table.wide100
            .cell.wide100
              = text_field_tag :box, nil,  autocomplete: 'off', placeholder: t('placeholder.add_to_new_list'), class: 'wide100 inline'
            .cell
              = button_tag class: 'inline noWrap' do
                <svg class='icon '><use xlink:href='#plus' /></svg>
      %li.switchHolder <svg class='icon linkLike switch' data-activate='#boxesList'><use xlink:href='#x'/></svg>        
    .tooltip
      .tip
      = t 'tooltip.list'
    %span#i_scroll.switch{'data-activate' => '#boxesList'}

app/views/polishes/_controls.html.haml
- with_text ||= false
- if with_text
  - if polish.lock
    .iconArray.withText<
      = link_to lock_path(polish.id), method: :post, remote: true do
        <svg class='icon hoverBack withText'><use xlink:href='#key' /></svg>
        = t 'controls.unlock'
  - else
    .iconArray.withText<
      = link_to edit_brand_polish_path(polish.brand_slug, polish.slug) do
        <svg class='icon hoverBack withText'><use xlink:href='#pencil'/></svg>
        = t 'controls.edit'
      = link_to_unless polish.draft, ("<svg class='icon hoverBack withText'><use xlink:href='#pour'/></svg>" + t( 'controls.redress')).html_safe, redress_brand_polish_path(polish.brand_slug, polish.slug) do
        = ''
      = link_to clone_brand_polish_path(polish.brand_slug, polish.slug), method: :post, remote: true do
        <svg class='icon hoverBack withText'><use xlink:href='#dolly'/></svg>
        = t 'controls.clone'
    .iconArray.withText<  
      = link_to lock_path(polish.id), method: :post, remote: true do
        <svg class='icon hoverBack withText'><use xlink:href='#lock' /></svg>
        = t 'controls.lock'
      = link_to brand_polish_path(polish.brand_slug, polish.slug), method: :delete, remote: params[:action] != 'show', data: { confirm: t('form.confirm_polish', polish: polish.name) } do
        <svg class='icon hoverBack withText'><use xlink:href='#trash'/></svg>
        = t 'controls.delete'
- else
  .iconArray<
    = link_to_if !polish.lock, "<svg class='icon hoverBack'><use xlink:href='#pencil'/></svg>".html_safe, edit_brand_polish_path(polish.brand_slug, polish.slug)
    = link_to_unless polish.lock || polish.draft, "<svg class='icon hoverBack'><use xlink:href='#pour'  /></svg>".html_safe, redress_brand_polish_path(polish.brand_slug, polish.slug)
    = link_to_if !polish.lock, "<svg class='icon hoverBack'><use xlink:href='#dolly' /></svg>".html_safe, clone_brand_polish_path(polish.brand_slug, polish.slug), method: :post, remote: true
    = link_to "<svg class='icon hoverBack'><use xlink:href='##{polish.lock ? 'key' : 'lock' }' /></svg>".html_safe, lock_path(polish.id), method: :post, remote: true
    = link_to_if !polish.lock, "<svg class='icon hoverBack'><use xlink:href='#trash' /></svg>".html_safe, brand_polish_path(polish.brand_slug, polish.slug), method: :delete, remote: true, data: { confirm: t('form.confirm_polish', polish: polish.name) }

app/views/polishes/_polish.html.haml
- unless polish == @polish
  - remove ||= params[:edit]
  - remove = remove && @box
  - add ||= false
  - add = add && @box
  - big_polish ||= (add || remove)
  - no_vote ||= add
  - no_brand = (@brand.try(:slug) == polish.brand_slug) if no_brand == nil
  - break_on_brand ||= false
  - if big_polish
    -if break_on_brand
      - @current_slug = polish.brand_slug
      - if @old_slug != @current_slug
        %h3= polish.brand_name
      - @old_slug = @current_slug
    .bigPolish{'data-id' => polish.id}>
      - if @box && current_user && @box.user_id == current_user.id
        - if add && @box
          = link_to collect_path(polish.id, box: @box.slug, from_list: true), method: :post, remote: true do
            = image_tag polish.bottle_url('big'), class: ('getBottlingStatus' unless polish.draft || polish.bottling_status)
            <svg class='icon button roundButton'><use xlink:href=#plus /></svg>
        - else
          = link_to (remove ? collect_path(polish.id, box: @box.slug, from_list: true) : catalogue_brand_polish_path(polish.brand_slug, polish.slug)), method: (remove ? 'post' : false), remote: remove do
            = image_tag polish.bottle_url('big'), class: ('getBottlingStatus' unless polish.draft || polish.bottling_status)
            <svg class='icon button roundButton important' style='#{('display:none' unless remove)}'><use xlink:href=#trash /></svg>    
      - else
        = link_to catalogue_brand_polish_path(polish.brand_slug, polish.slug) do
          = image_tag polish.bottle_url('big'), class: ('getBottlingStatus' unless polish.draft || polish.bottling_status)
      .info<
        %p.truncatable
          = link_to truncate(polish.name_or_number, length: 30, ), catalogue_brand_polish_path(polish.brand_slug, polish.slug)
          - if @notes && @notes[polish.id]
            %span *
        - unless no_vote
          .voteBox.relative.center
            = render 'stars', polish: polish
  - else
    .idBlock.polish.noFlow.bottomUp{'data-id' => polish.id}<
      = link_to image_tag( polish.bottle_url('thumb'), class: ('getBottlingStatus' unless polish.draft || polish.bottling_status)), (in_lab? ? brand_polish_path(polish.brand_slug, polish.slug) : catalogue_brand_polish_path(polish.brand_slug, polish.slug)), class: 'pic'
      .info
        - unless no_brand
          %p= link_to truncate(polish.brand_name, length: 50, omission: '…', separator: / |-|_/), (in_lab? ? brand_path(polish.brand_slug) : catalogue_path(polish.brand_slug))
        %p.truncatable
          %strong
            - if in_lab?
              = link_to ((polish.number + ' ' if polish.number).to_s + polish.name.to_s), brand_polish_path(polish.brand_slug, polish.slug)
            - else
              = link_to polish.name_or_number, catalogue_brand_polish_path(polish.brand_slug, polish.slug)
        - if in_lab?
          = render 'polishes/controls', polish: polish
        - elsif !no_vote
          %p.voteBox
            = render 'stars', polish: polish
    

app/views/polishes/_reference.html.haml
= image_tag(@polish.reference_url, id: 'reference_image', class: 'wide100')
= text_field_tag :output, '', id: 'output'

app/views/polishes/catalogue_show.html.haml
.main.left
  %h1.smallMargin
    = link_to @polish.brand_name, catalogue_brand_path( @polish.brand_slug)
    = truncate (' – ' + @polish.name_and_number), length: 50, separator: /_|-| /
  
  %h4
    - if @polish.collection
      = link_to @polish.collection, catalogue_brand_path(@polish.brand_slug, collection: @polish.collection)
    - if @polish.collection && @polish.release_year
      –
    - if @polish.release_year
      = link_to @polish.release_year, catalogue_brand_path(@polish.brand_slug, release_year: @polish.release_year)
      ,
    - @colour_names.each_with_index do |colour, i|
      = link_to( colour, catalogue_path(colour: colour)) + (i < @colour_names.size - 1 ? ', ' : '')
  .block.left{'data-id' => @polish.id}>
    = image_tag @polish.bottle_url, class: "left biggestBottle #{'getBottlingStatus' unless @polish.draft || @polish.bottling_status}"
    - unless @polish.draft
      #coatsWrapper.left
        .previewWrapper.medium= image_tag @polish.preview_url
  .block.left
    .idBlock.polishStats.bottomUp<
      .pic.relative>
        <svg class='star'> <use xlink:href='#star'/></svg>
        #rating= @polish.rating.round(1)
      .info>
        #voteBox.voteBox.tipped
          .tooltip{'data-s_1' => t('tooltip.one'),'data-s_2' => t('tooltip.two'),'data-s_3' => t('tooltip.three'),'data-s_4' => t('tooltip.four'),'data-s_5' => t('tooltip.five')}
            .tip
            %span OK
          = render 'stars', polish: @polish
        %p
          %span#votesCount= @polish.votes_count
          = 'vote'.pluralize( @polish.votes_count)
    - if current_user
      = render 'collections'  
      #note.resizable.relative{'data-polish_id' => @polish.id}
        = text_area_tag :body, current_user.notes.find_by_polish_id(@polish.id).try(:body) , placeholder: 'leave a note', class: 'resizable', rows: nil, cols: nil, id:'noteBody'
        %pre.resizable <span></span>
        
  %section
    %h2.clearFix= t 'comments.header'
    - unless params[:edit_id] || params[:reply_id]
      = render 'comments/form', comment: Comment.new, commentable: @polish
    #comments{'data-url' => request.original_url.split('?')[0]}= render @comments
  - if @related  
    %section
      %h2
        = t 'catalogue.titles.similar'
        = render_spread_slider
      #searchResults
        = render @related, no_brand: false
= render 'ads'
     

app/views/polishes/clone.js.haml
$('#searchResults').prepend('#{j(render @copy).html_safe}');
var polishes = $('#searchResults').children('.polish');
if( polishes.size() > 6){ polishes.last().remove(); }

app/views/polishes/collect.js.haml
- if params[:from_list]
  $('.bigPolish[data-id=#{params[:polish_id]}]').remove();
  - if @is_in
    $('#secondaryResults').append('#{j(render(@added_item, big_polish: true).html_safe)}');    
    if ($('#searchBrand').val() == '' && $('#searchPolish').val() == ''){
    - if @next_item
      console.log('add to results');
      $('#results').append('#{j(render(@next_item, add: true).html_safe)}');    
    } else {
    - if @next_item
      $('#searchResults').append('#{j(render(@next_item, add: true).html_safe)}');    
    }
-else
  - if %w(collection wishlist giveaway).include? @box.slug
    - if @is_in
      $('##{@box.slug}List').next('.icon').show();
    - else 
      $('##{@box.slug}List').next('.icon').hide();
  - else
    - if @box_is_new
      $('#boxesList').children('.formLi').before('<li class="notCurrent"><a id="#{@box.slug}List" data-remote="true" rel="nofollow" data-method="post" href="/collect/#{@item.polish_id}?box=#{@box.name}">#{@box.name} <svg class="icon isOk check"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#check"></use></svg><svg class="icon isOk plus" style="visibility: hidden;"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#plus"></use></svg></a></li>')
    - elsif @is_in
      $('##{@box.slug}List').children('.plus').first().css('visibility','hidden');
      $('##{@box.slug}List').children('.check').first().css('visibility','visible');
    - else
      $('##{@box.slug}List').children('.check').first().css('visibility','hidden');
      $('##{@box.slug}List').children('.plus').first().css('visibility','visible');

app/views/polishes/destroy.js.haml
$('.polish[data-id=#{@id}]').remove();

app/views/polishes/get_bottling_status.js.haml
var img = $('[data-id=#{@polish.id}]').find('.getBottlingStatus');
var thumb = '#{@polish.bottle_url('thumb')}';
var big = '#{@polish.bottle_url('big')}';
var src = '#{@polish.bottle_url}';
if (img.hasClass('big')){img.attr('src', big);} 
else if (img.hasClass('thumb')){img.attr('src', thumb);}
else {img.attr('src', src);}

app/views/polishes/index.html.haml
.main.left
  %h1.wide50.inline> 
    = t 'catalogue.headers.main'
  = render 'search', css: 'wide50 bigMargin completable', remote: true
  = render 'polishes/catalogue_search'
= render 'ads'

app/views/polishes/redress.html.haml
.block.main.left
  %h2 New polish
  = render 'form'